# Generated by Django 5.2.16 on 2026-07-24 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budget_category'),
        ('expense_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='expense_groups.expensegroup'),
        ),
    ]
