# Generated by Django 5.2.16 on 2026-07-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('housing', 'Housing'), ('health', 'Healthcare'), ('education', 'Education'), ('others', 'Others')], default='others', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('ocr_status', models.CharField(choices=[('none', 'No Receipt'), ('pending', 'Pending OCR'), ('completed', 'OCR Completed'), ('failed', 'OCR Failed')], default='none', max_length=15)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
