# Generated by Django 5.2.16 on 2026-07-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('others', 'Others')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Expense Outflow', max_length=200),
        ),
    ]
