# Generated by Django 5.2.16 on 2026-07-11 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '__first__'),
        ('expenses', '0003_expense_notes_expense_payment_method_expense_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='categories.category'),
        ),
    ]
