# Generated by Django 5.2.16 on 2026-07-24 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('expense_groups', '0001_initial'),
        ('expenses', '0004_alter_expense_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense_groups.expensegroup'),
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('others', 'Others')], default='cash', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('start_date', models.DateField(help_text='When the recurrence begins.')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank to repeat indefinitely.', null=True)),
                ('next_due_date', models.DateField(help_text='Next date the expense will be auto-generated.')),
                ('is_active', models.BooleanField(default=True)),
                ('total_generated', models.PositiveIntegerField(default=0, help_text='How many expenses have been generated so far.')),
                ('last_generated', models.DateField(blank=True, help_text='The date of the most recently generated expense.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_expense',
            field=models.ForeignKey(blank=True, help_text='If auto-generated from a recurring rule, links back to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='expenses.recurringexpense'),
        ),
    ]
